[package]
name = "rmg"
description = "Rails migration utility"
version = "0.1.1"
authors = ["Shunichi Ikegami <sike.tm@gmail.com>"]

[dependencies]
yaml-rust = "0.4.2"
postgres = "0.15.2"
regex = "1.1.0"
users = "0.8.1"
clap = "2.32.0"
itertools = "0.8.0"
